import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

import "./globals.css";

import MainLayout from "@/components/mainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const TabBarComponent = dynamic(() => import("../components/tabBar"), {
    ssr: false,
  });
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MainLayout />
        <TabBarComponent />
        {children}
      </body>
    </html>
  );
}
