import { CookiesProvider } from "react-cookie";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import MainLayout from "@/components/mainLayout";
import TabBar from "@/components/tabBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MainLayout />
        <div className="min-h-[calc(100vh-theme('spacing.mobile'))] sm:min-h-[calc(100vh-theme('spacing.web'))] flex items-stretch overflow-y-auto pb-[45px] sm:pb-0">
          {children}
        </div>
        <TabBar />
      </body>
    </html>
  );
}
